name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: udaydomadiya08/vantix
          huggingface_repo_id: UDAYDOMADIYA/vantix-core
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
